config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :messages, only: [:new, :create, :index]
  root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  before_create :create_remember_token
  has_secure_password 
  validates :password, length: { minimum: 6 }


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # only signed in users can create a new message 
  before_action :signed_in_user, only: [:new, :create]

  def index 
    @messages = Message.all 
  end 
  
  def new 
    @message = Message.new
  end 

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.save
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :body)
  end 


  def signed_in_user
    unless signed_in? 
      redirect_to signin_url
    end 
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Thank you for signing in!'
      sign_in user
      redirect_to root_path        
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end 
  end 

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end 

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out 
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end   

  def signed_in?
    !current_user.nil?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diyauth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<div class="float-right">
  <% if signed_in? %>
  <%= link_to "Sign out", signout_path, method: "delete" %>
  <% else %>
    <%= link_to 'Sign in', signin_path %>
  <% end %>
</div>

<h1>Members Only messages</h1>

<% @messages.each do |message| %>
    <p class="float-right">
      messaged by:
      <%= message.user.name %>
    </p>
  <h4 class="float-left"><%=message.title %></h4>  
  <p class="clear"><%= message.body %></p>
<% end %>

<% if signed_in? %>
  <%= link_to "Create a message", new_message_path %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= form_for @message do |f| %>

<p>
  <%= f.label :title %> <br/>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %><br />
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>